DEFRA/adp-portal

.azuredevops/build.yaml, app/package.json
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#213700](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/213700) and builds on #3376 (link to ADO Build ID URL)*
=> 278019: Sonar Test

.azuredevops/techdocs.yaml, README.md, app/app-config.production.yaml, app/app-config.yaml, app/package.json, app/packages/backend/src/DocsBuildStrategy.test.ts, app/packages/backend/src/plugins/techdocs.ts, app/packages/backend/src/plugins/techdocs/AnnotationBasedBuildStrategy.ts, app/packages/backend/src/plugins/techdocs/Techdocs.md
[AB#279550](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/279550) With the latest changes it is now possible to have both local build and pipeline based document generation sing the appropriate annotations. 
https://dev.azure.com/defragovuk/DEFRA-FFC/_build?definitionId=5604
=> 279550: Hybrid Strategy Techdocs

.azuredevops/build.yaml, app/package.json, app/packages/backend/Dockerfile
[AB#249199](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/249199)
=> 249199 : Deploy portal app to ssv5

app/package.json, app/packages/backend/src/permissions/policies/adpPortalPermissionPolicy.test.ts, app/packages/backend/src/permissions/rbacUtilites.test.ts
Refactored the units to execute quicker and to use jest.mock and spyOn
*Link to the relevant work items: e.g: Relates to ADO Work Item AB#274004and builds on #459235([https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=459235&view=results](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=459235&view=results))*
Tests run successfully locally and in the pipeline
=> 274004: Refactored unit tests to use spyOn and mock for class dependencies

.azuredevops/build.yaml, app/package.json, app/sonar-project.properties
*Link to the relevant work items: 
[AB#305166](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305166)
[AB#291239](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/291239)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=464021&view=results
=> 305166: Trigger for all branches including main

.azuredevops/build.yaml, app/package.json
*Link to the relevant work items: [AB#304330](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/304330)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=482788&view=results
=> 304330: add suffix to container app name

README.md
* Changes to readme, instructions for getting the portal to run on a mac.
No
No Code changes
=> Update instructions for mac users

.azuredevops/backstage.yaml, .azuredevops/build.yaml, app/package.json
Added appName parameter and changed to appKeyVaultName.
[AB#292476](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/292476)
=> 292476:AppName parameter

.azuredevops/build.yaml, app/package.json
*Link to the relevant work items: 
[AB#323021](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/323021)
Simplify the variable import from variable groups specific to environment
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=498488&view=results
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=498617&view=results
=> 323021: Variable Import

.azuredevops/build.yaml, app/package.json
*Link to the relevant work items:*
[AB#336334](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/336334)
1. construct container app name, managed identity and variable group names based on the app name.
2. Use <environment> string in variable groups instead of env names
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=502373&view=results
=> 336334: Container App Name

app/package.json, app/plugins/adp-backend/src/service/deliveryProgrammeRouter.test.ts, app/plugins/adp-backend/src/service/deliveryProgrammeRouter.ts, app/plugins/adp-backend/src/utils/index.test.ts, app/plugins/adp-backend/src/utils/index.ts, app/plugins/adp/src/components/DeliveryProgramme/CreateDeliveryProgramme.test.tsx, app/plugins/adp/src/components/DeliveryProgramme/CreateDeliveryProgramme.tsx, app/plugins/adp/src/components/DeliveryProgramme/DeliveryProgrammeFormFields.ts, app/plugins/adp/src/components/DeliveryProgramme/DeliveryProgrammeViewPageComponent.test.tsx, app/plugins/adp/src/components/DeliveryProgramme/DeliveryProgrammeViewPageComponent.tsx, app/plugins/adp/src/utils/DeliveryProgramme/DeliveryProgrammeUtils.ts
[AB#276865](https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/354567/) 
This PR adds validations on front end and back end to ensure that the title and programme code is unique when creating or editing an existing delivery programme.  
N/A
N/A
=> 276865: Validations for unique title and programme code in delivery programmes

app/package.json, app/plugins/scaffolder-backend-module-adp-scaffolder-actions/src/actions/github/createTeam.ts
We need to add in the Platform SA account. 
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=526769&view=results
=> Update createTeam.ts to add in Platform accounts

app/app-config.production.yaml, app/app-config.yaml, app/package.json
*Link to the relevant work items:*
[AB#353836](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/353836)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=528564&view=results
=> 358541 : Enable local non secure connection to api

.azuredevops/backstage.yaml, .azuredevops/build.yaml, app/package.json
Used latest varaible names of portal  auth appreg
[AB#355292](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/355292)
=> 355292: Rename ssv shared env resources

app/app-config.yaml, app/package.json, app/plugins/adp-backend/src/deliveryProject/fluxConfigApi.ts, app/plugins/adp/src/components/DeliveryProject/api/DeliveryProjectClient.test.ts, app/plugins/adp/src/components/DeliveryProject/api/DeliveryProjectClient.ts
This PR contains the below changes
- Updated flux config api endpoints
- Removed adding members to AD groups when creating delivery projects
- Updated unit tests for delivery projects
[AB#345221](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/345221)
=> 305682: Fixes for ad group members and update flux config api endpoints 

app/package.json, app/yarn.lock
Updates the version of mysql2 to fix the critical vulnerability associated with it.
[AB#362552](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/362552)
=> 362552: Update mysql2

app/package.json, app/plugins/adp/src/components/DeliveryProject/api/DeliveryProjectClient.ts
Update to the path used to call the backend api due to changes in DEFRA/adp-portal-api#21
[AB#305668](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305668)
=> 305668: Update url to match changes in API

app/package.json, app/plugins/adp/src/components/AdpData/LandingPageComponent.test.tsx, app/plugins/adp/src/components/AdpData/LandingPageComponent.tsx
Amends wording on ADP Onboarding page from Delivery Team to Delivery Project,  this aligns with endpoint naming and the pages title.
[#AD367627](https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/367627)
=> 367627: Changes Delivery Team to Delivery Projects on Onboarding Page

app/package.json, app/plugins/adp-backend/src/armsLengthBody/armsLengthBodyStore.ts
[AB#349167](https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/349167/)
* Addresses bug where users were getting 403/400 errors when updating url of an Arms Length Body
* update method was trying to update non existent column of 'children' from entity provider resulting in Knex error 'column "children" of relation "arms_length_body" does not exist'
*  Removal of 'children' field in the update method fixes error
*  Tested validity of entity links by adding new ALB, reassigning to a seeded delivery programme, to demonstrate children/parent linkage not effected by this PR change
* comment raised 24/03 that url with https results in 403 and url http 400 error but error appears to be resolved with above change.
*Any relevant testing …
=> 349167: Bug Fix: Updating ALB url

.azuredevops/backstage.yaml, app/package.json
Updated to use release 1.0.1 for adp-software-templates.
This includes the support to generate flux service manifests for helm only template.
[AB#346049](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/346049)
=> 346049: Updated adp-sofware-templates tag v1.0.1

app/package.json, app/packages/app/src/components/catalog/EntityPage.tsx, app/packages/app/src/setupTests.ts
[AB#373487](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/373487) Fixes an issue on some entity tabs caused by #101 Tests will come in a later PR as this fix is needed pretty urgently.
=> Fix entity page runtime error

app/package.json, app/plugins/adp-backend/seedData/delivery_programme.js
Updated delivery programmes seeded data specifically the _delivery_programme_code_ field. This will ensure that the project name field will be correct on creation due to the prefix being the delivery_programme_code.
[AB#370853](https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/370853/) .
=> 370853: Updated delivery_programme_code & name:  ffc, eutd, crai

.azuredevops/backstage.yaml, app/package.json
Updated software template version to 1.0.3 to include changes to add teamName to the pipeline in templates.
[AB#369368](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/369368)
=> 369368: Update software template release version to 1.0.3

app/package.json, app/plugins/adp/src/components/DeliveryProgramme/DeliveryProgrammeViewPageComponent.tsx, app/plugins/adp/src/components/DeliveryProgramme/__snapshots__/DeliveryProgrammeViewPageComponent.test.tsx.snap, app/plugins/adp/src/components/DeliveryProject/DeliveryProjectViewPageComponent.test.tsx, app/plugins/adp/src/components/DeliveryProject/DeliveryProjectViewPageComponent.tsx, app/plugins/adp/src/components/DeliveryProject/__snapshots__/DeliveryProjectViewPageComponent.test.tsx.snap
Link delivery projects to catalog entity page. [AB#361230](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/361230)
=> 361230: Delivery project links

app/package.json, app/packages/app/src/App.tsx, app/packages/app/src/style.module.scss
[AB#381671](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/381671) Update the dark mode styles to be more consistent with light mode
Before:
After:
=> 381671: Update styles

.devcontainer/compose.yaml, .devcontainer/devcontainer.json, .vscode/launch.json, app/.eslintrc.js, app/.prettierignore, app/compose.dev.yaml, app/compose.postgres.yaml, app/package.json, app/packages/app/e2e-tests/app.test.ts, app/packages/app/src/App.test.tsx, app/packages/app/src/__snapshots__/App.test.tsx.snap, app/packages/app/src/components/Root/Root.tsx, app/packages/app/src/components/catalog/EntityPage.test.tsx, app/plugins/adp-backend/package.json, app/plugins/adp/src/hooks/useArmsLengthBodyList.tsx, app/plugins/adp/src/hooks/useCatalogUsersList.tsx, app/plugins/scaffolder-backend-module-adp-scaffolder-actions/src/filters/toDotnetProjectName.ts, app/tsconfig.json, app/yarn.lock
Fixes errors with linting, prettier and the e2e tests, as well as adding some docker compose files to make it easy to spin up a postgres db
=> Fix lint, prettier, and e2e test errors

.azuredevops/backstage.yaml, app/package.json
This PR contains changes to update adp software templates release version.
[AB#275171](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/275171)
To be merged only after https://github.com/DEFRA/adp-software-templates/pull/61 is completed and Release 1.1.2 is created.
=> 275171: Update software template release version

.azuredevops/backstage.yaml, app/package.json
[AB#378196](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/378196) Update template version
=> 378196: Update software templates version

app/app-config.production.yaml, app/package.json, app/plugins/adp/src/components/DeliveryProject/api/DeliveryProjectClient.ts
Updates payload for creating Entra ID groups when creating projects. [AB#361609](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/361609)
- [] This PR contains documentation
=> 361609: Payload for creating Entra ID groups

.azuredevops/backstage.yaml, app/package.json
Updated the portal to use adp-software-templates release 1.1.5, which contains the fix to make the AppInsights config names same as nodejs.
[AB#275171](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/275171)
To be merged after the PR https://github.com/DEFRA/adp-software-templates/pull/64 and release 1.1.5 is created
=> 275171: Fixes to dotnet backend in software templates

.azuredevops/backstage.yaml, app/app-config.production.yaml, app/package.json
Updates to use release 1.1.6 of software templates which contains the updates to postgres 15 and other fixes
[AB#309469](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/309469)
To be merged after PR https://github.com/DEFRA/adp-software-templates/pull/65 is completed and release 1.1.6 is created
=> 309469: Release 1.1.6 of software template - postgres 15

.azuredevops/backstage.yaml, app/app-config.yaml, app/package.json, app/plugins/adp-backend/src/deliveryProject/fluxConfigApi.test.ts
Added CONTAINER_MAX_CPU and CONTAINER_MAX_MEMORY in defaultConfigVariables
Relates to ADO Work Item [AB#383608](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/383608)
[adp-teams-config/flux/services/fcp-gg-test.yaml at main · defra-adp-sandpit/adp-teams-config (github.com)](https://github.com/defra-adp-sandpit/adp-teams-config/blob/main/flux/services/fcp-gg-test.yaml)
=> 383608: Added CONTAINER_MAX_CPU and CONTAINER_MAX_MEMORY in defaultConfigVariables

.azuredevops/backstage.yaml, app/package.json
Fixed helm only issues
[AB#393544](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/393544)
=> 393544: Fixed helm only issues

app/package.json, app/yarn.lock
[AB#382055](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/382055) deduplicates a bunch of packages to fix some errors due to multiple loaded versions of the same library
=> 382055: Fix duplicated packages

.azuredevops/backstage.yaml, app/package.json
[AB#338313](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/338313) This PR updates the version of software templates to its latest version
=> 338313: Update template versions

app/app-config.yaml, app/package.json
[AB#311150](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/311150) Updates configuration to reduce the polling interval of catalog-info.yaml
=> 311150: Github catalog ratelimit

app/plugins/adp-ai-chatbot/package.json, app/plugins/adp-ai-chatbot/src/components/ChatUI.tsx, app/plugins/adp-ai-chatbot/src/components/Chatbot.tsx, app/yarn.lock
POC items;
* markdown 
* improved styling
=> Ah/poc/cosmetic UI changes

app/app-config.yaml, app/package.json
[AB#311150](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/311150) Filters out any repositories without a catalog-info.yaml
=> 311150: Filter out invalid repos

.azuredevops/backstage.yaml, app/package.json
*Link to the relevant work items: *
[AB#311150](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/311150)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=585328&view=results
=> 311150: App Insights cloudrole Seperated per env

app/app-config.production.yaml, app/app-config.yaml, app/package.json, app/plugins/adp-backend/src/AdpClient.test.ts, app/plugins/adp-backend/src/AdpClient.ts, app/plugins/request-context-provider-backend/src/RequestContextMiddleware.test.ts, app/plugins/request-context-provider-backend/src/RequestContextMiddleware.ts, app/plugins/request-context-provider-backend/src/index.ts, app/plugins/request-context-provider-backend/src/requestContextMiddlewareRef.ts, app/plugins/request-context-provider-backend/src/requestContextProviderFactory.ts, app/plugins/scaffolder-backend-module-adp/package.json, app/plugins/scaffolder-backend-module-adp/src/actions/github/addDeliveryProjectToRepo.test.ts, app/plugins/scaffolder-backend-module-adp/src/actions/github/addDeliveryProjectToRepo.ts, app/plugins/scaffolder-backend-module-adp/src/module.ts, app/yarn.lock
[AB#353928](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/353928) Fixes an authentication issue with the scaffolder trying to talk to the c# backend.
[AB#311150](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/311150) Now that repositories are ignored if they dont contain a catalog-info.yaml, we no longer need to only look at a small subset of the repositories, so the filters have been removed.
=> 353928: Fix scaffolder and remove repository filter

.azuredevops/backstage.yaml, app/package.json
*Link to the relevant work items: *
[AB#366306](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/366306)
=> 366306: snd4 kubernetes tab fix

.azuredevops/backstage.yaml, app/package.json
Updates the version of software templates being used to fix an issue with the scaffolded frontend tests
=> Update template version

app/package.json, app/plugins/adp/src/components/DeliveryProgrammeAdmin/DeliveryProgrammeAdminFormFields.test.tsx, app/plugins/adp/src/components/DeliveryProgrammeAdmin/__snapshots__/DeliveryProgrammeAdminFormFields.test.tsx.snap, app/plugins/adp/src/components/DeliveryProjectUser/DeliveryProjectUserFormFields.test.tsx
[AB#376110](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/376110) fixes some tests which have a race condition causing them to be a bit flaky
=> 376110: Fix failing tests

.azuredevops/backstage.yaml, app/package.json
Updates portal to use the latest template version.
=> Bump templates version and fix sonar coverage

.vscode/settings.json, app/app-config.yaml, app/package.json, app/plugins/adp-backend/config.d.ts, app/plugins/adp-backend/src/deliveryProject/adoProjectApi.test.ts, app/plugins/adp-backend/src/deliveryProject/adoProjectApi.ts, app/plugins/adp-backend/src/deliveryProject/index.ts, app/plugins/adp-backend/src/plugin.test.ts, app/plugins/adp-backend/src/plugin.ts, app/plugins/adp-backend/src/service/deliveryProjectRouter.test.ts, app/plugins/adp-backend/src/service/deliveryProjectRouter.ts, app/plugins/adp-common/src/index.ts, app/plugins/adp-common/src/types/ado-project.ts, app/plugins/adp/src/components/DeliveryProject/api/DeliveryProjectClient.test.ts, app/plugins/adp/src/components/DeliveryProject/api/DeliveryProjectClient.ts
Handle duplicate teams exceptions. Moved portal API calls from frontend to adp-backend.
[AB#399252](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/399252)
=> 399252: Handle duplicate teams

app/package.json, app/plugins/adp/src/utils/reservedUsernames.ts
Case insensitive validation for github handle for reserved usernames
[AB#397668](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/397668)
=> 397668: BugFix - Github handle validation in delivery project user

app/package.json, app/plugins/scaffolder-backend-module-adp/src/actions/backend/configureAdoProject.test.ts, app/plugins/scaffolder-backend-module-adp/src/actions/backend/createBackendApiAction.ts, app/plugins/scaffolder-backend-module-adp/src/actions/backend/generateServiceManifests.test.ts, app/plugins/scaffolder-backend-module-adp/src/actions/backend/registerFluxService.test.ts
[AB#353928](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/353928) Adds some missed tests
=> 353928: Add unit tests

app/package.json, app/plugins/scaffolder-backend-module-adp/src/filters/githubRepoUrl.test.ts, app/plugins/scaffolder-backend-module-adp/src/filters/githubRepoUrl.ts
[AB#399260](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/399260) Fixes a format issue with the new githubRepoUrl filter
=> 399260: Fix github repo url

.azuredevops/backstage.yaml, app/package.json
Updates the software templates version to use the new service connection
=> Bump template version

app/package.json, app/plugins/adp-backend/src/routes/armsLengthBodies/create.test.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/create.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/edit.test.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/edit.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/errorMapping.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/get.test.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/get.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/getAll.test.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/getAll.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/getNames.test.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/getNames.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/health.test.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/health.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/index.test.ts, app/plugins/adp-backend/src/routes/armsLengthBodies/index.ts, app/plugins/adp-backend/src/routes/checkAuth.ts, app/plugins/adp-backend/src/routes/util/HandlerResult.ts, app/plugins/adp-backend/src/routes/util/createEndpointRef.ts, app/plugins/adp-backend/src/routes/util/routerResultsRef.ts, app/plugins/adp-backend/src/utils/testHelpers.ts
[AB#371568](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/371568) Migrate the ALB router to the new style
=> 371568: Implement new style alb router

app/package.json, app/packages/app/src/components/Root/Root.tsx, app/plugins/adp/src/components/ALB/AlbViewPageComponent.test.tsx, app/plugins/adp/src/components/ALB/AlbViewPageComponent.tsx, app/plugins/adp/src/components/ALB/__snapshots__/AlbViewPageComponent.test.tsx.snap, app/plugins/adp/src/components/DeliveryProgramme/DeliveryProgrammeViewPageComponent.test.tsx, app/plugins/adp/src/components/DeliveryProgramme/DeliveryProgrammeViewPageComponent.tsx, app/plugins/adp/src/components/DeliveryProgramme/__snapshots__/DeliveryProgrammeViewPageComponent.test.tsx.snap, app/plugins/adp/src/components/DeliveryProgrammeAdmin/DeliveryProgrammeAdminViewPage.test.tsx, app/plugins/adp/src/components/DeliveryProgrammeAdmin/DeliveryProgrammeAdminViewPage.tsx, app/plugins/adp/src/components/DeliveryProgrammeAdmin/__snapshots__/DeliveryProgrammeAdminViewPage.test.tsx.snap, app/plugins/adp/src/components/DeliveryProject/DeliveryProjectViewPageComponent.test.tsx, app/plugins/adp/src/components/DeliveryProject/DeliveryProjectViewPageComponent.tsx, app/plugins/adp/src/components/DeliveryProject/__snapshots__/DeliveryProjectViewPageComponent.test.tsx.snap, app/plugins/adp/src/components/DeliveryProjectUser/DeliveryProjectUserViewPage.test.tsx, app/plugins/adp/src/components/DeliveryProjectUser/DeliveryProjectUserViewPage.tsx, app/plugins/adp/src/components/DeliveryProjectUser/__snapshots__/DeliveryProjectUserViewPage.test.tsx.snap, app/plugins/adp/src/utils/DefaultTable.tsx
[AB#380580](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/380580) Updates the tables to be more consistent and accessible.
=> 380580: Updates to various tables

app/package.json, app/plugins/adp-backend/src/routes/catalog/arms-length-bodies/get.yaml.ts, app/plugins/adp-backend/src/routes/catalog/delivery-programmes/get.yaml.ts, app/plugins/adp-backend/src/routes/catalog/delivery-projects/get.yaml.test.ts, app/plugins/adp-backend/src/routes/catalog/delivery-projects/get.yaml.ts, app/plugins/adp-backend/src/routes/catalog/util.ts, app/plugins/adp-common/src/util/annotations.ts, app/plugins/adp-common/src/util/index.ts, app/plugins/catalog-backend-module-adp/src/index.ts, app/plugins/catalog-backend-module-adp/src/module.test.ts, app/plugins/catalog-backend-module-adp/src/module.ts, app/plugins/catalog-backend-module-adp/src/processors/DeliveryProjectProcessor.test.ts, app/plugins/catalog-backend-module-adp/src/processors/DeliveryProjectProcessor.ts, app/plugins/catalog-backend-module-adp/src/processors/index.ts, app/plugins/permission-backend-module-adp/src/policies/adpPortalPermissionPolicy.test.ts, app/plugins/permission-backend-module-adp/src/roles/scaffolderUsersRole.test.ts, app/plugins/permission-backend-module-adp/src/roles/scaffolderUsersRole.ts, app/plugins/scaffolder-adp-react/config.d.ts, app/plugins/scaffolder-adp-react/package.json, app/plugins/scaffolder-adp-react/src/components/DeliveryProjectPicker/DeliveryProjectPicker.test.tsx, app/plugins/scaffolder-adp-react/src/components/DeliveryProjectPicker/DeliveryProjectPicker.tsx, app/plugins/scaffolder-adp-react/src/components/DeliveryProjectPicker/__snapshots__/DeliveryProjectPicker.test.tsx.snap, app/plugins/scaffolder-adp-react/src/components/DeliveryProjectPicker/useDeliveryProjects.test.tsx, app/plugins/scaffolder-adp-react/src/components/DeliveryProjectPicker/useDeliveryProjects.tsx, app/yarn.lock
[AB#391772](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/391772) Allows ADP admins to scaffold for any project. Also restricts users to scaffolding only for services they are a tech member of.
=> 391772: Update what delivery projects are shown

app/package.json, app/plugins/scaffolder-adp-react/src/components/DeliveryProjectPicker/DeliveryProjectPicker.test.tsx, app/plugins/scaffolder-adp-react/src/components/DeliveryProjectPicker/DeliveryProjectPicker.tsx, app/plugins/scaffolder-adp-react/src/components/DeliveryProjectPicker/__snapshots__/DeliveryProjectPicker.test.tsx.snap, app/plugins/scaffolder-adp-react/src/components/DeliveryProjectPicker/useDeliveryProjects.test.tsx, app/plugins/scaffolder-adp-react/src/components/DeliveryProjectPicker/useDeliveryProjects.tsx
[AB#391772](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/391772) Changes how the error message shows when there are no projects available.
=> 391772: Update error when no projects are available

.azuredevops/backstage.yaml, app/package.json
_A brief description of changes being made_
Bump templates version to the latest
=> Bump templates version

.github/pull_request_template.md, README.md, package.json, plugins/adp/src/components/DeliveryProject/DeliveryProjectFormFields.tsx, plugins/adp/src/components/DeliveryProjectUser/DeliveryProjectUserViewPage.tsx, plugins/adp/src/components/DeliveryProjectUser/__snapshots__/DeliveryProjectUserViewPage.test.tsx.snap, plugins/adp/src/hooks/useDeliveryProgrammesList.test.tsx, plugins/adp/src/hooks/useDeliveryProgrammesList.tsx
_A brief description of changes being made_
[AB#414680](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/414680) Update the labels for the edit delivery project modal
[AB#377626](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/377626) Ensure that the list of delivery programmes includes the currently selected delivery programme when editing a delivery project
=> Delivery Project modal fixes

package.json, plugins/permission-backend-module-adp/src/mocks/rbacTestData.ts, plugins/permission-backend-module-adp/src/module.ts, plugins/permission-backend-module-adp/src/policies/adpPortalPermissionPolicy.test.ts, plugins/permission-backend-module-adp/src/policies/adpPortalPermissionPolicy.ts, plugins/permission-backend-module-adp/src/rbacUtilites.test.ts, plugins/permission-backend-module-adp/src/rbacUtilites.ts, plugins/permission-backend-module-adp/src/roles/deliveryProgrammeAdminMangerRole.test.ts, plugins/permission-backend-module-adp/src/roles/deliveryProgrammeCreatorRole.test.ts, plugins/permission-backend-module-adp/src/roles/deliveryProgrammeEditorRole.test.ts, plugins/permission-backend-module-adp/src/roles/deliveryProjectCreatorRole.test.ts, plugins/permission-backend-module-adp/src/roles/deliveryProjectEditorRole.test.ts, plugins/permission-backend-module-adp/src/roles/deliveryProjectUserManagerRole.test.ts, plugins/permission-backend-module-adp/src/roles/platformAdminRole.test.ts, plugins/permission-backend-module-adp/src/roles/scaffolderUsersRole.test.ts, plugins/permission-backend-module-adp/src/roles/scaffolderUsersRole.ts, plugins/permission-backend-module-adp/src/types.ts
[AB#398668](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/398668) Corrects the permissions around the scaffolder so that only technical team members can scaffold services
=> 398668: Scaffolder permission fix

.azuredevops/backstage.yaml, app-config.yaml, package.json
[AB#417336](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/417336) Adds the files to allow projects to define their own un-versioned systems. Systems are defined within the root `/systems` folder
=> 417336: Add support for projects defining their own systems

app-config.yaml, package.json
[AB#417336](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/417336) Fixes an issue introduced by the previous catalog changes.
=> 417336: Fix catalog
